name: start mALLke
on:
  schedule:
    - cron:  '16 20 * * *'    
env:
  isecFold: 'insec/'
  workFold: '/opt/'
  webFold: 'docs/'
  prjFold: 'out/'   
  repoName: 'mALLkeOld'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }} 
    - name: base install
      run: |
            sudo apt-get update
            sudo apt-get install -y p7zip-full unzip wget iftop nmon
            (cd ${{env.isecFold}}&&sudo 7z x archive.7z -p${{secrets.GIT_PASS}} -o${{env.workFold}})    
            sudo apt-get install -y git python3 python3-pandas python3-pip python3-setuptools
            sudo apt-get install -y python3-dev python3-pip python3-venv python3-wheel
            sudo pip3 install wheel
            sudo -H pip3 install --ignore-installed PyYAML 
            sudo pip3 install pybadges
            mkdir /tmp/works           
    - name: base works
      run: |
           sudo python3 ${{env.workFold}}${{env.repoName}}_1jv.py ${{env.workFold}} > /dev/null 2>&1
